version: "3.7"
services:
  app:
    image: node-js-1-example:15-slim
    build: .
    ports:
      - 3000:3000
  app-alpine:
    image: node-js-1-example:15-alpine
    build:
      context: .
      args:
        NODE_IMAGE_VERSION: 15-alpine
    ports:
      - 3001:3000
