apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    release: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      release: {{.Release.Name}}
  replicas: {{.Values.replicas}}
  template:
    metadata:
      annotations:
        release.revison: "{{.Release.Revision}}"
      labels:
        release: {{.Release.Name}}
    spec:
      containers:
        - name: main
          image: {{required "Required value for: image" .Values.image}}
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 20m
              memory: 200Mi
