image: sikalabs/ci

stages:
  - lint
  - build
  - deploy dev
  - test dev
  - deploy prod

variables:
  NODE_JS_1_IMAGE: $CI_REGISTRY_IMAGE/node-js-1:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

prettier node-js-1:
  stage: lint
  image: node
  variables:
    GIT_CLEAN_FLAGS: -ffdx -e node_modules
  script:
    - cd node-js-1
    - yarn
    - yarn run prettier-check

build node-js-1:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $NODE_JS_1_IMAGE ./node-js-1
    - docker push $NODE_JS_1_IMAGE

deploy dev node-js-1:
  stage: deploy dev
  script:
    - helm upgrade --install node-$CI_COMMIT_REF_SLUG ./charts/node-js-1
      --wait
      --set host=$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
      --set image=$NODE_JS_1_IMAGE
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop dev node-js-1

stop dev node-js-1:
  stage: deploy dev
  when: manual
  allow_failure: false
  variables:
    GIT_STRATEGY: none
  script:
    - helm uninstall node-$CI_COMMIT_REF_SLUG
  environment:
    name: dev/$CI_COMMIT_REF_SLUG
    action: stop

test dev:
  stage: test dev
  needs:
    - deploy dev node-js-1
  script:
    - curl -i https://$CI_COMMIT_REF_SLUG.$DEV_BASE_DOMAIN

deploy prod node-js-1:
  stage: deploy prod
  when: manual
  needs:
    - test dev
  script:
    - helm upgrade --install node-js-1 ./charts/node-js-1
      --wait
      --set host=node-js-1.$KUBE_INGRESS_BASE_DOMAIN
      --set image=$NODE_JS_1_IMAGE
  environment:
    name: prod
    url: https://node-js-1.$KUBE_INGRESS_BASE_DOMAIN
  only:
    - master
    - ci
