apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: reg.istry.cz/trz/node-js-1
      context: ./node-js-1
      kaniko: {}
    - image: reg.istry.cz/trz/go-1
      context: ./go-1
      kaniko: {}
    - image: reg.istry.cz/trz/dotnet-1
      context: ./dotnet-1
      kaniko: {}
  cluster: {}
deploy:
  helm:
    releases:
      - name: node-js-1
        chartPath: ./charts/node-js-1
        artifactOverrides:
          image: reg.istry.cz/trz/node-js-1
        valuesFiles:
          - ./.local-helm-values/node-js-1.yml
      - name: go
        chartPath: ./charts/go-1
        artifactOverrides:
          image: reg.istry.cz/trz/go-1
        valuesFiles:
          - ./.local-helm-values/go-1.yml
      - name: dotnet-1
        chartPath: ./charts/dotnet-1
        artifactOverrides:
          image: reg.istry.cz/trz/dotnet-1
        valuesFiles:
          - ./.local-helm-values/dotnet-1.yml
